from odoo import api, models, fields, _, tools
from datetime import datetime, timedelta, date
from odoo.exceptions import UserError, except_orm, ValidationError, Warning
from odoo import http
from odoo.http import content_disposition, request
import io
import xlsxwriter
import base64
import urllib3
from dateutil import relativedelta

class kb_mrp_sawmil(http.Controller):
    @http.route(['/kb_mrp_sawmil_report/<model("kb.mrp.sawmil.report"):wizard>',], type='http', auth="user", csrf=False)
    def get_kb_mrp_sawmil_report_excel(self, wizard=None, **args):
        response = request.make_response(
            None,
            headers=[
                ('Content-Type', 'application/vnd.ms-excel'),
                ('Content-Disposition', content_disposition('Sawmil Report' + '.xlsx'))
            ]
        )

        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {'in_memory': True})

        for rec1 in wizard:
            sheet = workbook.add_worksheet("Rekap Hasil Gesek")
            sheet.set_landscape()
            sheet.set_paper(9)

            header_table_format_white = workbook.add_format()
            header_table_format_white.set_font_name('Arial')
            header_table_format_white.set_font_size(12)
            header_table_format_white.set_align('center')
            header_table_format_white.set_align('vcenter')
            header_table_format_white.set_top(1)
            header_table_format_white.set_left(1)
            header_table_format_white.set_right(1)
            header_table_format_white.set_bottom(1)
            header_table_format_white.set_bold()

            isi_table_mid_format = workbook.add_format()
            isi_table_mid_format.set_font_name('Arial')
            isi_table_mid_format.set_font_size(12)
            isi_table_mid_format.set_align('center')
            isi_table_mid_format.set_align('vcenter')
            isi_table_mid_format.set_top(1)
            isi_table_mid_format.set_left(1)
            isi_table_mid_format.set_right(1)
            isi_table_mid_format.set_bottom(1)

            isi_table_right_format = workbook.add_format()
            isi_table_right_format.set_font_name('Arial')
            isi_table_right_format.set_font_size(12)
            isi_table_right_format.set_align('right')
            isi_table_right_format.set_align('vcenter')
            isi_table_right_format.set_top(1)
            isi_table_right_format.set_left(1)
            isi_table_right_format.set_right(1)
            isi_table_right_format.set_bottom(1)

            sheet.set_column('A:A', 20)
            sheet.set_column('B:B', 20)
            sheet.set_column('C:C', 20)
            sheet.set_column('D:D', 20)
            sheet.set_column('E:E', 20)
            sheet.set_column('F:F', 20)
            sheet.set_column('G:G', 20)
            sheet.set_column('H:H', 20)

            sheet.write(0, 0, 'No. Nota', header_table_format_white)
            sheet.write(0, 1, 'Jenis Kayu', header_table_format_white)
            sheet.write(0, 2, 'Kode', header_table_format_white)
            sheet.write(0, 3, 'Log Pakai (Pcs)', header_table_format_white)
            sheet.write(0, 4, 'Log Pakai (M3)', header_table_format_white)
            sheet.write(0, 5, 'Hasil Keping', header_table_format_white)
            sheet.write(0, 6, 'Hasil (M3)', header_table_format_white)
            sheet.write(0, 7, 'RENDEMEN', header_table_format_white)

            row1 = 1
            report_lines = request.env['kb.mrp.sawmil.report.line'].sudo().search(
                [('kb_mrp_sawmil_report_id', '=', rec1.id)],
                order="kb_mrp_sawmil_id, kb_mrp_sawmil_line_id, kb_mrp_sawmil_line_detail_id asc")
            for line in report_lines:
                if line.log_pakai_m3 > 0:
                    rendemen = str(round((line.hasil_m3 / line.log_pakai_m3) * 100, 0))+"%"
                else:
                    rendemen = "0%"
                sheet.write(row1, 0, line.name_header, isi_table_mid_format)
                sheet.write(row1, 1, line.jenis_kayu, isi_table_mid_format)
                sheet.write(row1, 2, line.kode, isi_table_mid_format)
                sheet.write(row1, 3, line.log_pakai_pcs, isi_table_right_format)
                sheet.write(row1, 4, line.log_pakai_m3, isi_table_right_format)
                sheet.write(row1, 5, line.hasil_keping, isi_table_right_format)
                sheet.write(row1, 6, line.hasil_m3, isi_table_right_format)
                sheet.write(row1, 7, rendemen, isi_table_right_format)
                row1 += 1

        for rec2 in wizard:
            sheet = workbook.add_worksheet("Rincian Hasil Gesek")
            sheet.set_landscape()
            sheet.set_paper(9)

            header_table_format_kuning = workbook.add_format()
            header_table_format_kuning.set_font_name('Arial')
            header_table_format_kuning.set_font_size(12)
            header_table_format_kuning.set_align('center')
            header_table_format_kuning.set_align('vcenter')
            header_table_format_kuning.set_top(1)
            header_table_format_kuning.set_left(1)
            header_table_format_kuning.set_right(1)
            header_table_format_kuning.set_bottom(1)
            header_table_format_kuning.set_bold()
            header_table_format_kuning.set_bg_color('#f0e973')

            header_table_format_coklat = workbook.add_format()
            header_table_format_coklat.set_font_name('Arial')
            header_table_format_coklat.set_font_size(12)
            header_table_format_coklat.set_align('center')
            header_table_format_coklat.set_align('vcenter')
            header_table_format_coklat.set_top(1)
            header_table_format_coklat.set_left(1)
            header_table_format_coklat.set_right(1)
            header_table_format_coklat.set_bottom(1)
            header_table_format_coklat.set_bold()
            header_table_format_coklat.set_bg_color('#ada184')

            header_table_format_hijau = workbook.add_format()
            header_table_format_hijau.set_font_name('Arial')
            header_table_format_hijau.set_font_size(12)
            header_table_format_hijau.set_align('center')
            header_table_format_hijau.set_align('vcenter')
            header_table_format_hijau.set_top(1)
            header_table_format_hijau.set_left(1)
            header_table_format_hijau.set_right(1)
            header_table_format_hijau.set_bottom(1)
            header_table_format_hijau.set_bold()
            header_table_format_hijau.set_bg_color('#83c977')

            header_table_format_biru = workbook.add_format()
            header_table_format_biru.set_font_name('Arial')
            header_table_format_biru.set_font_size(12)
            header_table_format_biru.set_align('center')
            header_table_format_biru.set_align('vcenter')
            header_table_format_biru.set_top(1)
            header_table_format_biru.set_left(1)
            header_table_format_biru.set_right(1)
            header_table_format_biru.set_bottom(1)
            header_table_format_biru.set_bold()
            header_table_format_biru.set_bg_color('#5096e6')

            header_table_format_white = workbook.add_format()
            header_table_format_white.set_font_name('Arial')
            header_table_format_white.set_font_size(12)
            header_table_format_white.set_align('center')
            header_table_format_white.set_align('vcenter')
            header_table_format_white.set_top(1)
            header_table_format_white.set_left(1)
            header_table_format_white.set_right(1)
            header_table_format_white.set_bottom(1)
            header_table_format_white.set_bold()


            isi_table_mid_format_kuning = workbook.add_format()
            isi_table_mid_format_kuning.set_font_name('Arial')
            isi_table_mid_format_kuning.set_font_size(12)
            isi_table_mid_format_kuning.set_align('center')
            isi_table_mid_format_kuning.set_align('vcenter')
            isi_table_mid_format_kuning.set_top(1)
            isi_table_mid_format_kuning.set_left(1)
            isi_table_mid_format_kuning.set_right(1)
            isi_table_mid_format_kuning.set_bottom(1)
            isi_table_mid_format_kuning.set_bg_color('#f0e973')

            isi_table_mid_format_coklat = workbook.add_format()
            isi_table_mid_format_coklat.set_font_name('Arial')
            isi_table_mid_format_coklat.set_font_size(12)
            isi_table_mid_format_coklat.set_align('center')
            isi_table_mid_format_coklat.set_align('vcenter')
            isi_table_mid_format_coklat.set_top(1)
            isi_table_mid_format_coklat.set_left(1)
            isi_table_mid_format_coklat.set_right(1)
            isi_table_mid_format_coklat.set_bottom(1)
            isi_table_mid_format_coklat.set_bg_color('#ada184')

            isi_table_mid_format_biru = workbook.add_format()
            isi_table_mid_format_biru.set_font_name('Arial')
            isi_table_mid_format_biru.set_font_size(12)
            isi_table_mid_format_biru.set_align('center')
            isi_table_mid_format_biru.set_align('vcenter')
            isi_table_mid_format_biru.set_top(1)
            isi_table_mid_format_biru.set_left(1)
            isi_table_mid_format_biru.set_right(1)
            isi_table_mid_format_biru.set_bottom(1)
            isi_table_mid_format_biru.set_bg_color('#5096e6')

            isi_table_right_format_hijau = workbook.add_format()
            isi_table_right_format_hijau.set_font_name('Arial')
            isi_table_right_format_hijau.set_font_size(12)
            isi_table_right_format_hijau.set_align('right')
            isi_table_right_format_hijau.set_align('vcenter')
            isi_table_right_format_hijau.set_top(1)
            isi_table_right_format_hijau.set_left(1)
            isi_table_right_format_hijau.set_right(1)
            isi_table_right_format_hijau.set_bottom(1)
            isi_table_right_format_hijau.set_bg_color('#83c977')

            isi_table_right_format_biru = workbook.add_format()
            isi_table_right_format_biru.set_font_name('Arial')
            isi_table_right_format_biru.set_font_size(12)
            isi_table_right_format_biru.set_align('right')
            isi_table_right_format_biru.set_align('vcenter')
            isi_table_right_format_biru.set_top(1)
            isi_table_right_format_biru.set_left(1)
            isi_table_right_format_biru.set_right(1)
            isi_table_right_format_biru.set_bottom(1)
            isi_table_right_format_biru.set_bg_color('#5096e6')

            isi_table_left_format = workbook.add_format()
            isi_table_left_format.set_font_name('Arial')
            isi_table_left_format.set_font_size(12)
            isi_table_left_format.set_align('left')
            isi_table_left_format.set_align('vcenter')
            isi_table_left_format.set_top(1)
            isi_table_left_format.set_left(1)
            isi_table_left_format.set_right(1)
            isi_table_left_format.set_bottom(1)

            sheet.set_column('A:A', 20)
            sheet.set_column('B:B', 20)
            sheet.set_column('C:C', 20)
            sheet.set_column('D:D', 20)
            sheet.set_column('E:E', 20)
            sheet.set_column('F:F', 20)
            sheet.set_column('G:G', 20)
            sheet.set_column('H:H', 20)
            sheet.set_column('I:I', 20)
            sheet.set_column('J:J', 20)
            sheet.set_column('K:K', 20)
            sheet.set_column('L:L', 20)
            sheet.set_column('M:M', 20)
            sheet.set_column('N:N', 20)
            sheet.set_column('O:O', 20)
            sheet.set_column('P:P', 20)

            sheet.write(0, 0, 'Tgl. Gesek', header_table_format_kuning)
            sheet.write(0, 1, 'No. Note', header_table_format_kuning)
            sheet.write(0, 2, 'Jenis Kayu', header_table_format_coklat)
            sheet.write(0, 3, 'Kode', header_table_format_coklat)
            sheet.write(0, 4, 'Diameter 1', header_table_format_hijau)
            sheet.write(0, 5, 'Diameter 2', header_table_format_hijau)
            sheet.write(0, 6, 'Panjang', header_table_format_hijau)
            sheet.write(0, 7, 'Log Pakai (Pcs)', header_table_format_hijau)
            sheet.write(0, 8, 'Log Pakai (M3)', header_table_format_hijau)
            sheet.write(0, 9, 'Tebal', header_table_format_biru)
            sheet.write(0, 10, 'Lebar', header_table_format_biru)
            sheet.write(0, 11, 'Panjang', header_table_format_biru)
            sheet.write(0, 12, 'Hasil Keping', header_table_format_biru)
            sheet.write(0, 13, 'Hasil (M3)', header_table_format_biru)
            sheet.write(0, 14, 'Shift', header_table_format_biru)
            sheet.write(0, 15, 'Keterangan', header_table_format_white)

            row2 = 1
            report_lines = request.env['kb.mrp.sawmil.report.line'].sudo().search([('kb_mrp_sawmil_report_id', '=', rec2.id)], order="kb_mrp_sawmil_id, kb_mrp_sawmil_line_id, kb_mrp_sawmil_line_detail_id asc")
            for line in report_lines:
                get_tanggal_gesek_awal = datetime.strptime(str(line.tanggal_gesek), "%Y-%m-%d")
                get_tanggal_gesek = get_tanggal_gesek_awal.strftime("%d/%m/%Y")
                sheet.write(row2, 0, str(get_tanggal_gesek), isi_table_mid_format_kuning)
                sheet.write(row2, 1, line.name_header, isi_table_mid_format_kuning)
                sheet.write(row2, 2, line.jenis_kayu, isi_table_mid_format_coklat)
                sheet.write(row2, 3, line.kode, isi_table_mid_format_coklat)
                sheet.write(row2, 4, line.diameter1, isi_table_right_format_hijau)
                sheet.write(row2, 5, line.diameter2, isi_table_right_format_hijau)
                sheet.write(row2, 6, line.panjang_line, isi_table_right_format_hijau)
                sheet.write(row2, 7, line.log_pakai_pcs, isi_table_right_format_hijau)
                sheet.write(row2, 8, line.log_pakai_m3, isi_table_right_format_hijau)
                sheet.write(row2, 9, line.tebal, isi_table_right_format_biru)
                sheet.write(row2, 10, line.lebar, isi_table_right_format_biru)
                sheet.write(row2, 11, line.panjang_detail, isi_table_right_format_biru)
                sheet.write(row2, 12, line.hasil_keping, isi_table_right_format_biru)
                sheet.write(row2, 13, line.hasil_m3, isi_table_right_format_biru)
                sheet.write(row2, 14, line.shift, isi_table_mid_format_biru)
                sheet.write(row2, 15, line.keterangan, isi_table_left_format)
                row2 += 1
        workbook.close()
        output.seek(0)
        response.stream.write(output.read())
        output.close()
        return response



class kb_mrp_vakum_celup(http.Controller):
    @http.route(['/kb_mrp_vakum_celup_report/<model("kb.mrp.vakum.celup.report"):wizard>',], type='http', auth="user", csrf=False)
    def get_kb_mrp_vakum_celup_report_excel(self, wizard=None, **args):
        response = request.make_response(
            None,
            headers=[
                ('Content-Type', 'application/vnd.ms-excel'),
                ('Content-Disposition', content_disposition('Vakum Celup Report' + '.xlsx'))
            ]
        )

        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {'in_memory': True})

        for rec1 in wizard:
            sheet = workbook.add_worksheet("Rekap Hasil Vakum Celup")
            sheet.set_landscape()
            sheet.set_paper(9)

            header_table_format_white = workbook.add_format()
            header_table_format_white.set_font_name('Arial')
            header_table_format_white.set_font_size(12)
            header_table_format_white.set_align('center')
            header_table_format_white.set_align('vcenter')
            header_table_format_white.set_top(1)
            header_table_format_white.set_left(1)
            header_table_format_white.set_right(1)
            header_table_format_white.set_bottom(1)
            header_table_format_white.set_bold()

            isi_table_mid_format = workbook.add_format()
            isi_table_mid_format.set_font_name('Arial')
            isi_table_mid_format.set_font_size(12)
            isi_table_mid_format.set_align('center')
            isi_table_mid_format.set_align('vcenter')
            isi_table_mid_format.set_top(1)
            isi_table_mid_format.set_left(1)
            isi_table_mid_format.set_right(1)
            isi_table_mid_format.set_bottom(1)

            isi_table_right_format = workbook.add_format()
            isi_table_right_format.set_font_name('Arial')
            isi_table_right_format.set_font_size(12)
            isi_table_right_format.set_align('right')
            isi_table_right_format.set_align('vcenter')
            isi_table_right_format.set_top(1)
            isi_table_right_format.set_left(1)
            isi_table_right_format.set_right(1)
            isi_table_right_format.set_bottom(1)

            sheet.set_column('A:A', 20)
            sheet.set_column('B:B', 20)
            sheet.set_column('C:C', 20)
            sheet.set_column('D:D', 20)
            sheet.set_column('E:E', 20)
            sheet.set_column('F:F', 20)
            sheet.set_column('G:G', 20)
            sheet.set_column('H:H', 20)

            sheet.write(0, 0, 'No. Nota', header_table_format_white)
            sheet.write(0, 1, 'Jenis Kayu', header_table_format_white)
            sheet.write(0, 2, 'Kode', header_table_format_white)
            sheet.write(0, 3, 'Log Pakai (Pcs)', header_table_format_white)
            sheet.write(0, 4, 'Log Pakai (M3)', header_table_format_white)
            sheet.write(0, 5, 'Hasil Keping', header_table_format_white)
            sheet.write(0, 6, 'Hasil (M3)', header_table_format_white)
            sheet.write(0, 7, 'RENDEMEN', header_table_format_white)

            row1 = 1
            report_lines = request.env['kb.mrp.vakum.celup.report.line'].sudo().search(
                [('vakum_celup_report_id', '=', rec1.id)],
                order="kb_mrp_vakum_celup_id, kb_mrp_vakum_celup_line_id, kb_mrp_vakum_celup_line_detail_id asc")
            for line in report_lines:
                if line.log_pakai_m3 > 0:
                    rendemen = str(round((line.hasil_m3 / line.log_pakai_m3) * 100, 0))+"%"
                else:
                    rendemen = "0%"
                sheet.write(row1, 0, line.name_header, isi_table_mid_format)
                sheet.write(row1, 1, line.jenis_kayu, isi_table_mid_format)
                sheet.write(row1, 2, line.kode, isi_table_mid_format)
                sheet.write(row1, 3, line.log_pakai_pcs, isi_table_right_format)
                sheet.write(row1, 4, line.log_pakai_m3, isi_table_right_format)
                sheet.write(row1, 5, line.hasil_keping, isi_table_right_format)
                sheet.write(row1, 6, line.hasil_m3, isi_table_right_format)
                sheet.write(row1, 7, rendemen, isi_table_right_format)
                row1 += 1

        for rec2 in wizard:
            sheet = workbook.add_worksheet("Rincian Hasil Vakum Celup")
            sheet.set_landscape()
            sheet.set_paper(9)

            header_table_format_kuning = workbook.add_format()
            header_table_format_kuning.set_font_name('Arial')
            header_table_format_kuning.set_font_size(12)
            header_table_format_kuning.set_align('center')
            header_table_format_kuning.set_align('vcenter')
            header_table_format_kuning.set_top(1)
            header_table_format_kuning.set_left(1)
            header_table_format_kuning.set_right(1)
            header_table_format_kuning.set_bottom(1)
            header_table_format_kuning.set_bold()
            header_table_format_kuning.set_bg_color('#f0e973')

            header_table_format_coklat = workbook.add_format()
            header_table_format_coklat.set_font_name('Arial')
            header_table_format_coklat.set_font_size(12)
            header_table_format_coklat.set_align('center')
            header_table_format_coklat.set_align('vcenter')
            header_table_format_coklat.set_top(1)
            header_table_format_coklat.set_left(1)
            header_table_format_coklat.set_right(1)
            header_table_format_coklat.set_bottom(1)
            header_table_format_coklat.set_bold()
            header_table_format_coklat.set_bg_color('#ada184')

            header_table_format_hijau = workbook.add_format()
            header_table_format_hijau.set_font_name('Arial')
            header_table_format_hijau.set_font_size(12)
            header_table_format_hijau.set_align('center')
            header_table_format_hijau.set_align('vcenter')
            header_table_format_hijau.set_top(1)
            header_table_format_hijau.set_left(1)
            header_table_format_hijau.set_right(1)
            header_table_format_hijau.set_bottom(1)
            header_table_format_hijau.set_bold()
            header_table_format_hijau.set_bg_color('#83c977')

            header_table_format_biru = workbook.add_format()
            header_table_format_biru.set_font_name('Arial')
            header_table_format_biru.set_font_size(12)
            header_table_format_biru.set_align('center')
            header_table_format_biru.set_align('vcenter')
            header_table_format_biru.set_top(1)
            header_table_format_biru.set_left(1)
            header_table_format_biru.set_right(1)
            header_table_format_biru.set_bottom(1)
            header_table_format_biru.set_bold()
            header_table_format_biru.set_bg_color('#5096e6')

            header_table_format_white = workbook.add_format()
            header_table_format_white.set_font_name('Arial')
            header_table_format_white.set_font_size(12)
            header_table_format_white.set_align('center')
            header_table_format_white.set_align('vcenter')
            header_table_format_white.set_top(1)
            header_table_format_white.set_left(1)
            header_table_format_white.set_right(1)
            header_table_format_white.set_bottom(1)
            header_table_format_white.set_bold()


            isi_table_mid_format_kuning = workbook.add_format()
            isi_table_mid_format_kuning.set_font_name('Arial')
            isi_table_mid_format_kuning.set_font_size(12)
            isi_table_mid_format_kuning.set_align('center')
            isi_table_mid_format_kuning.set_align('vcenter')
            isi_table_mid_format_kuning.set_top(1)
            isi_table_mid_format_kuning.set_left(1)
            isi_table_mid_format_kuning.set_right(1)
            isi_table_mid_format_kuning.set_bottom(1)
            isi_table_mid_format_kuning.set_bg_color('#f0e973')

            isi_table_mid_format_coklat = workbook.add_format()
            isi_table_mid_format_coklat.set_font_name('Arial')
            isi_table_mid_format_coklat.set_font_size(12)
            isi_table_mid_format_coklat.set_align('center')
            isi_table_mid_format_coklat.set_align('vcenter')
            isi_table_mid_format_coklat.set_top(1)
            isi_table_mid_format_coklat.set_left(1)
            isi_table_mid_format_coklat.set_right(1)
            isi_table_mid_format_coklat.set_bottom(1)
            isi_table_mid_format_coklat.set_bg_color('#ada184')

            isi_table_mid_format_biru = workbook.add_format()
            isi_table_mid_format_biru.set_font_name('Arial')
            isi_table_mid_format_biru.set_font_size(12)
            isi_table_mid_format_biru.set_align('center')
            isi_table_mid_format_biru.set_align('vcenter')
            isi_table_mid_format_biru.set_top(1)
            isi_table_mid_format_biru.set_left(1)
            isi_table_mid_format_biru.set_right(1)
            isi_table_mid_format_biru.set_bottom(1)
            isi_table_mid_format_biru.set_bg_color('#5096e6')

            isi_table_right_format_hijau = workbook.add_format()
            isi_table_right_format_hijau.set_font_name('Arial')
            isi_table_right_format_hijau.set_font_size(12)
            isi_table_right_format_hijau.set_align('right')
            isi_table_right_format_hijau.set_align('vcenter')
            isi_table_right_format_hijau.set_top(1)
            isi_table_right_format_hijau.set_left(1)
            isi_table_right_format_hijau.set_right(1)
            isi_table_right_format_hijau.set_bottom(1)
            isi_table_right_format_hijau.set_bg_color('#83c977')

            isi_table_right_format_biru = workbook.add_format()
            isi_table_right_format_biru.set_font_name('Arial')
            isi_table_right_format_biru.set_font_size(12)
            isi_table_right_format_biru.set_align('right')
            isi_table_right_format_biru.set_align('vcenter')
            isi_table_right_format_biru.set_top(1)
            isi_table_right_format_biru.set_left(1)
            isi_table_right_format_biru.set_right(1)
            isi_table_right_format_biru.set_bottom(1)
            isi_table_right_format_biru.set_bg_color('#5096e6')

            isi_table_left_format = workbook.add_format()
            isi_table_left_format.set_font_name('Arial')
            isi_table_left_format.set_font_size(12)
            isi_table_left_format.set_align('left')
            isi_table_left_format.set_align('vcenter')
            isi_table_left_format.set_top(1)
            isi_table_left_format.set_left(1)
            isi_table_left_format.set_right(1)
            isi_table_left_format.set_bottom(1)

            sheet.set_column('A:A', 20)
            sheet.set_column('B:B', 20)
            sheet.set_column('C:C', 20)
            sheet.set_column('D:D', 20)
            sheet.set_column('E:E', 20)
            sheet.set_column('F:F', 20)
            sheet.set_column('G:G', 20)
            sheet.set_column('H:H', 20)
            sheet.set_column('I:I', 20)
            sheet.set_column('J:J', 20)
            sheet.set_column('K:K', 20)
            sheet.set_column('L:L', 20)
            sheet.set_column('M:M', 20)
            sheet.set_column('N:N', 20)
            sheet.set_column('O:O', 20)
            sheet.set_column('P:P', 20)
            sheet.set_column('Q:Q', 20)
            sheet.set_column('R:R', 20)
            sheet.set_column('S:S', 20)

            sheet.write(0, 0, 'Tgl. Selesai Vakum', header_table_format_kuning)
            sheet.write(0, 1, 'No. Note', header_table_format_kuning)
            sheet.write(0, 2, 'Jenis Kayu', header_table_format_coklat)
            sheet.write(0, 3, 'Kode', header_table_format_coklat)
            sheet.write(0, 4, 'Diameter 1', header_table_format_hijau)
            sheet.write(0, 5, 'Diameter 2', header_table_format_hijau)
            sheet.write(0, 6, 'Panjang', header_table_format_hijau)
            sheet.write(0, 7, 'Log Pakai (Pcs)', header_table_format_hijau)
            sheet.write(0, 8, 'Log Pakai (M3)', header_table_format_hijau)
            sheet.write(0, 9, 'Tebal', header_table_format_biru)
            sheet.write(0, 10, 'Lebar', header_table_format_biru)
            sheet.write(0, 11, 'Panjang', header_table_format_biru)
            sheet.write(0, 12, 'Hasil Keping', header_table_format_biru)
            sheet.write(0, 13, 'Hasil (M3)', header_table_format_biru)
            sheet.write(0, 14, 'Shift', header_table_format_biru)
            sheet.write(0, 15, 'Grade', header_table_format_biru)
            sheet.write(0, 16, 'FSC', header_table_format_biru)
            sheet.write(0, 17, 'Vakum / Celup', header_table_format_biru)
            sheet.write(0, 18, 'Keterangan', header_table_format_white)

            row2 = 1
            report_lines = request.env['kb.mrp.vakum.celup.report.line'].sudo().search([('vakum_celup_report_id', '=', rec2.id)], order="kb_mrp_vakum_celup_id, kb_mrp_vakum_celup_line_id, kb_mrp_vakum_celup_line_detail_id asc")
            for line in report_lines:
                get_tanggal_selesai_vakum_awal = datetime.strptime(str(line.tanggal_selesai_vakum), "%Y-%m-%d")
                get_tanggal_selesai_vakum = get_tanggal_selesai_vakum_awal.strftime("%d/%m/%Y")
                sheet.write(row2, 0, str(get_tanggal_selesai_vakum), isi_table_mid_format_kuning)
                sheet.write(row2, 1, line.name_header, isi_table_mid_format_kuning)
                sheet.write(row2, 2, line.jenis_kayu, isi_table_mid_format_coklat)
                sheet.write(row2, 3, line.kode, isi_table_mid_format_coklat)
                sheet.write(row2, 4, line.diameter1, isi_table_right_format_hijau)
                sheet.write(row2, 5, line.diameter2, isi_table_right_format_hijau)
                sheet.write(row2, 6, line.panjang_line, isi_table_right_format_hijau)
                sheet.write(row2, 7, line.log_pakai_pcs, isi_table_right_format_hijau)
                sheet.write(row2, 8, line.log_pakai_m3, isi_table_right_format_hijau)
                sheet.write(row2, 9, line.tebal, isi_table_right_format_biru)
                sheet.write(row2, 10, line.lebar, isi_table_right_format_biru)
                sheet.write(row2, 11, line.panjang_detail, isi_table_right_format_biru)
                sheet.write(row2, 12, line.hasil_keping, isi_table_right_format_biru)
                sheet.write(row2, 13, line.hasil_m3, isi_table_right_format_biru)
                sheet.write(row2, 14, line.shift, isi_table_mid_format_biru)
                sheet.write(row2, 15, line.grade, isi_table_mid_format_biru)
                sheet.write(row2, 16, line.fsc, isi_table_mid_format_biru)
                sheet.write(row2, 17, line.vakum_celup, isi_table_mid_format_biru)
                sheet.write(row2, 18, line.keterangan, isi_table_left_format)
                row2 += 1
        workbook.close()
        output.seek(0)
        response.stream.write(output.read())
        output.close()
        return response

class kb_mrp_sticking(http.Controller):
    @http.route(['/kb_mrp_sticking_report/<model("kb.mrp.sticking.report"):wizard>',], type='http', auth="user", csrf=False)
    def get_kb_mrp_sticking_report_excel(self, wizard=None, **args):
        response = request.make_response(
            None,
            headers=[
                ('Content-Type', 'application/vnd.ms-excel'),
                ('Content-Disposition', content_disposition('Sticking Report' + '.xlsx'))
            ]
        )

        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {'in_memory': True})

        for rec1 in wizard:
            sheet = workbook.add_worksheet("Rekap Hasil Sticking")
            sheet.set_landscape()
            sheet.set_paper(9)

            header_table_format_white = workbook.add_format()
            header_table_format_white.set_font_name('Arial')
            header_table_format_white.set_font_size(12)
            header_table_format_white.set_align('center')
            header_table_format_white.set_align('vcenter')
            header_table_format_white.set_top(1)
            header_table_format_white.set_left(1)
            header_table_format_white.set_right(1)
            header_table_format_white.set_bottom(1)
            header_table_format_white.set_bold()

            isi_table_mid_format = workbook.add_format()
            isi_table_mid_format.set_font_name('Arial')
            isi_table_mid_format.set_font_size(12)
            isi_table_mid_format.set_align('center')
            isi_table_mid_format.set_align('vcenter')
            isi_table_mid_format.set_top(1)
            isi_table_mid_format.set_left(1)
            isi_table_mid_format.set_right(1)
            isi_table_mid_format.set_bottom(1)

            isi_table_right_format = workbook.add_format()
            isi_table_right_format.set_font_name('Arial')
            isi_table_right_format.set_font_size(12)
            isi_table_right_format.set_align('right')
            isi_table_right_format.set_align('vcenter')
            isi_table_right_format.set_top(1)
            isi_table_right_format.set_left(1)
            isi_table_right_format.set_right(1)
            isi_table_right_format.set_bottom(1)

            sheet.set_column('A:A', 20)
            sheet.set_column('B:B', 20)
            sheet.set_column('C:C', 20)
            sheet.set_column('D:D', 20)
            sheet.set_column('E:E', 20)
            sheet.set_column('F:F', 20)
            sheet.set_column('G:G', 20)
            sheet.set_column('H:H', 20)

            sheet.write(0, 0, 'No. Nota', header_table_format_white)
            sheet.write(0, 1, 'Jenis Kayu', header_table_format_white)
            sheet.write(0, 2, 'Kode', header_table_format_white)
            sheet.write(0, 3, 'Log Pakai (Pcs)', header_table_format_white)
            sheet.write(0, 4, 'Log Pakai (M3)', header_table_format_white)
            sheet.write(0, 5, 'Hasil Keping', header_table_format_white)
            sheet.write(0, 6, 'Hasil (M3)', header_table_format_white)
            sheet.write(0, 7, 'RENDEMEN', header_table_format_white)

            row1 = 1
            report_lines = request.env['kb.mrp.sticking.report.line'].sudo().search(
                [('sticking_report_id', '=', rec1.id)],
                order="kb_mrp_sticking_id, kb_mrp_sticking_line_id, kb_mrp_sticking_line_detail_id asc")
            for line in report_lines:
                if line.log_pakai_m3 > 0:
                    rendemen = str(round((line.hasil_m3 / line.log_pakai_m3) * 100, 0))+"%"
                else:
                    rendemen = "0%"
                sheet.write(row1, 0, line.name_header, isi_table_mid_format)
                sheet.write(row1, 1, line.jenis_kayu, isi_table_mid_format)
                sheet.write(row1, 2, line.kode, isi_table_mid_format)
                sheet.write(row1, 3, line.log_pakai_pcs, isi_table_right_format)
                sheet.write(row1, 4, line.log_pakai_m3, isi_table_right_format)
                sheet.write(row1, 5, line.hasil_keping, isi_table_right_format)
                sheet.write(row1, 6, line.hasil_m3, isi_table_right_format)
                sheet.write(row1, 7, rendemen, isi_table_right_format)
                row1 += 1

        for rec2 in wizard:
            sheet = workbook.add_worksheet("Rincian Hasil Sticking")
            sheet.set_landscape()
            sheet.set_paper(9)

            header_table_format_kuning = workbook.add_format()
            header_table_format_kuning.set_font_name('Arial')
            header_table_format_kuning.set_font_size(12)
            header_table_format_kuning.set_align('center')
            header_table_format_kuning.set_align('vcenter')
            header_table_format_kuning.set_top(1)
            header_table_format_kuning.set_left(1)
            header_table_format_kuning.set_right(1)
            header_table_format_kuning.set_bottom(1)
            header_table_format_kuning.set_bold()
            header_table_format_kuning.set_bg_color('#f0e973')

            header_table_format_coklat = workbook.add_format()
            header_table_format_coklat.set_font_name('Arial')
            header_table_format_coklat.set_font_size(12)
            header_table_format_coklat.set_align('center')
            header_table_format_coklat.set_align('vcenter')
            header_table_format_coklat.set_top(1)
            header_table_format_coklat.set_left(1)
            header_table_format_coklat.set_right(1)
            header_table_format_coklat.set_bottom(1)
            header_table_format_coklat.set_bold()
            header_table_format_coklat.set_bg_color('#ada184')

            header_table_format_hijau = workbook.add_format()
            header_table_format_hijau.set_font_name('Arial')
            header_table_format_hijau.set_font_size(12)
            header_table_format_hijau.set_align('center')
            header_table_format_hijau.set_align('vcenter')
            header_table_format_hijau.set_top(1)
            header_table_format_hijau.set_left(1)
            header_table_format_hijau.set_right(1)
            header_table_format_hijau.set_bottom(1)
            header_table_format_hijau.set_bold()
            header_table_format_hijau.set_bg_color('#83c977')

            header_table_format_biru = workbook.add_format()
            header_table_format_biru.set_font_name('Arial')
            header_table_format_biru.set_font_size(12)
            header_table_format_biru.set_align('center')
            header_table_format_biru.set_align('vcenter')
            header_table_format_biru.set_top(1)
            header_table_format_biru.set_left(1)
            header_table_format_biru.set_right(1)
            header_table_format_biru.set_bottom(1)
            header_table_format_biru.set_bold()
            header_table_format_biru.set_bg_color('#5096e6')

            header_table_format_white = workbook.add_format()
            header_table_format_white.set_font_name('Arial')
            header_table_format_white.set_font_size(12)
            header_table_format_white.set_align('center')
            header_table_format_white.set_align('vcenter')
            header_table_format_white.set_top(1)
            header_table_format_white.set_left(1)
            header_table_format_white.set_right(1)
            header_table_format_white.set_bottom(1)
            header_table_format_white.set_bold()


            isi_table_mid_format_kuning = workbook.add_format()
            isi_table_mid_format_kuning.set_font_name('Arial')
            isi_table_mid_format_kuning.set_font_size(12)
            isi_table_mid_format_kuning.set_align('center')
            isi_table_mid_format_kuning.set_align('vcenter')
            isi_table_mid_format_kuning.set_top(1)
            isi_table_mid_format_kuning.set_left(1)
            isi_table_mid_format_kuning.set_right(1)
            isi_table_mid_format_kuning.set_bottom(1)
            isi_table_mid_format_kuning.set_bg_color('#f0e973')

            isi_table_mid_format_coklat = workbook.add_format()
            isi_table_mid_format_coklat.set_font_name('Arial')
            isi_table_mid_format_coklat.set_font_size(12)
            isi_table_mid_format_coklat.set_align('center')
            isi_table_mid_format_coklat.set_align('vcenter')
            isi_table_mid_format_coklat.set_top(1)
            isi_table_mid_format_coklat.set_left(1)
            isi_table_mid_format_coklat.set_right(1)
            isi_table_mid_format_coklat.set_bottom(1)
            isi_table_mid_format_coklat.set_bg_color('#ada184')

            isi_table_mid_format_biru = workbook.add_format()
            isi_table_mid_format_biru.set_font_name('Arial')
            isi_table_mid_format_biru.set_font_size(12)
            isi_table_mid_format_biru.set_align('center')
            isi_table_mid_format_biru.set_align('vcenter')
            isi_table_mid_format_biru.set_top(1)
            isi_table_mid_format_biru.set_left(1)
            isi_table_mid_format_biru.set_right(1)
            isi_table_mid_format_biru.set_bottom(1)
            isi_table_mid_format_biru.set_bg_color('#5096e6')

            isi_table_right_format_hijau = workbook.add_format()
            isi_table_right_format_hijau.set_font_name('Arial')
            isi_table_right_format_hijau.set_font_size(12)
            isi_table_right_format_hijau.set_align('right')
            isi_table_right_format_hijau.set_align('vcenter')
            isi_table_right_format_hijau.set_top(1)
            isi_table_right_format_hijau.set_left(1)
            isi_table_right_format_hijau.set_right(1)
            isi_table_right_format_hijau.set_bottom(1)
            isi_table_right_format_hijau.set_bg_color('#83c977')

            isi_table_right_format_biru = workbook.add_format()
            isi_table_right_format_biru.set_font_name('Arial')
            isi_table_right_format_biru.set_font_size(12)
            isi_table_right_format_biru.set_align('right')
            isi_table_right_format_biru.set_align('vcenter')
            isi_table_right_format_biru.set_top(1)
            isi_table_right_format_biru.set_left(1)
            isi_table_right_format_biru.set_right(1)
            isi_table_right_format_biru.set_bottom(1)
            isi_table_right_format_biru.set_bg_color('#5096e6')

            isi_table_left_format = workbook.add_format()
            isi_table_left_format.set_font_name('Arial')
            isi_table_left_format.set_font_size(12)
            isi_table_left_format.set_align('left')
            isi_table_left_format.set_align('vcenter')
            isi_table_left_format.set_top(1)
            isi_table_left_format.set_left(1)
            isi_table_left_format.set_right(1)
            isi_table_left_format.set_bottom(1)

            sheet.set_column('A:A', 20)
            sheet.set_column('B:B', 20)
            sheet.set_column('C:C', 20)
            sheet.set_column('D:D', 20)
            sheet.set_column('E:E', 20)
            sheet.set_column('F:F', 20)
            sheet.set_column('G:G', 20)
            sheet.set_column('H:H', 20)
            sheet.set_column('I:I', 20)
            sheet.set_column('J:J', 20)
            sheet.set_column('K:K', 20)
            sheet.set_column('L:L', 20)
            sheet.set_column('M:M', 20)
            sheet.set_column('N:N', 20)
            sheet.set_column('O:O', 20)
            sheet.set_column('P:P', 20)
            sheet.set_column('Q:Q', 20)
            sheet.set_column('R:R', 20)
            sheet.set_column('S:S', 20)

            sheet.write(0, 0, 'Tgl. Selesai Vakum', header_table_format_kuning)
            sheet.write(0, 1, 'Tgl. Selesai Stick', header_table_format_kuning)
            sheet.write(0, 2, 'No. Note', header_table_format_kuning)
            sheet.write(0, 3, 'Jenis Kayu', header_table_format_coklat)
            sheet.write(0, 4, 'Kode', header_table_format_coklat)
            sheet.write(0, 5, 'Diameter 1', header_table_format_hijau)
            sheet.write(0, 6, 'Diameter 2', header_table_format_hijau)
            sheet.write(0, 7, 'Panjang', header_table_format_hijau)
            sheet.write(0, 8, 'Log Pakai (Pcs)', header_table_format_hijau)
            sheet.write(0, 9, 'Log Pakai (M3)', header_table_format_hijau)
            sheet.write(0, 10, 'Tebal', header_table_format_biru)
            sheet.write(0, 11, 'Lebar', header_table_format_biru)
            sheet.write(0, 12, 'Panjang', header_table_format_biru)
            sheet.write(0, 13, 'Hasil Keping', header_table_format_biru)
            sheet.write(0, 14, 'Hasil (M3)', header_table_format_biru)
            sheet.write(0, 15, 'Shift', header_table_format_biru)
            sheet.write(0, 16, 'Grade', header_table_format_biru)
            sheet.write(0, 17, 'FSC', header_table_format_biru)
            sheet.write(0, 18, 'Keterangan', header_table_format_white)

            row2 = 1
            report_lines = request.env['kb.mrp.sticking.report.line'].sudo().search([('sticking_report_id', '=', rec2.id)], order="kb_mrp_sticking_id, kb_mrp_sticking_line_id, kb_mrp_sticking_line_detail_id asc")
            for line in report_lines:
                get_tanggal_selesai_vakum_awal = datetime.strptime(str(line.tanggal_selesai_vakum), "%Y-%m-%d")
                get_tanggal_selesai_vakum = get_tanggal_selesai_vakum_awal.strftime("%d/%m/%Y")
                get_tanggal_selesai_stick_awal = datetime.strptime(str(line.tanggal_selesai_stick), "%Y-%m-%d")
                get_tanggal_selesai_stick = get_tanggal_selesai_stick_awal.strftime("%d/%m/%Y")
                sheet.write(row2, 0, str(get_tanggal_selesai_vakum), isi_table_mid_format_kuning)
                sheet.write(row2, 1, str(get_tanggal_selesai_stick), isi_table_mid_format_kuning)
                sheet.write(row2, 2, line.name_header, isi_table_mid_format_kuning)
                sheet.write(row2, 3, line.jenis_kayu, isi_table_mid_format_coklat)
                sheet.write(row2, 4, line.kode, isi_table_mid_format_coklat)
                sheet.write(row2, 5, line.diameter1, isi_table_right_format_hijau)
                sheet.write(row2, 6, line.diameter2, isi_table_right_format_hijau)
                sheet.write(row2, 7, line.panjang_line, isi_table_right_format_hijau)
                sheet.write(row2, 8, line.log_pakai_pcs, isi_table_right_format_hijau)
                sheet.write(row2, 9, line.log_pakai_m3, isi_table_right_format_hijau)
                sheet.write(row2, 10, line.tebal, isi_table_right_format_biru)
                sheet.write(row2, 11, line.lebar, isi_table_right_format_biru)
                sheet.write(row2, 12, line.panjang_detail, isi_table_right_format_biru)
                sheet.write(row2, 13, line.hasil_keping, isi_table_right_format_biru)
                sheet.write(row2, 14, line.hasil_m3, isi_table_right_format_biru)
                sheet.write(row2, 15, line.shift, isi_table_mid_format_biru)
                sheet.write(row2, 16, line.grade, isi_table_mid_format_biru)
                sheet.write(row2, 17, line.fsc, isi_table_mid_format_biru)
                sheet.write(row2, 18, line.keterangan, isi_table_left_format)
                row2 += 1
        workbook.close()
        output.seek(0)
        response.stream.write(output.read())
        output.close()
        return response

class kb_mrp_oven(http.Controller):
    @http.route(['/kb_mrp_oven_report/<model("kb.mrp.oven.report"):wizard>',], type='http', auth="user", csrf=False)
    def get_kb_mrp_oven_report_excel(self, wizard=None, **args):
        response = request.make_response(
            None,
            headers=[
                ('Content-Type', 'application/vnd.ms-excel'),
                ('Content-Disposition', content_disposition('Oven Report' + '.xlsx'))
            ]
        )

        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {'in_memory': True})

        for rec1 in wizard:
            sheet = workbook.add_worksheet("Rekap Hasil Oven")
            sheet.set_landscape()
            sheet.set_paper(9)

            header_table_format_white = workbook.add_format()
            header_table_format_white.set_font_name('Arial')
            header_table_format_white.set_font_size(12)
            header_table_format_white.set_align('center')
            header_table_format_white.set_align('vcenter')
            header_table_format_white.set_top(1)
            header_table_format_white.set_left(1)
            header_table_format_white.set_right(1)
            header_table_format_white.set_bottom(1)
            header_table_format_white.set_bold()

            isi_table_mid_format = workbook.add_format()
            isi_table_mid_format.set_font_name('Arial')
            isi_table_mid_format.set_font_size(12)
            isi_table_mid_format.set_align('center')
            isi_table_mid_format.set_align('vcenter')
            isi_table_mid_format.set_top(1)
            isi_table_mid_format.set_left(1)
            isi_table_mid_format.set_right(1)
            isi_table_mid_format.set_bottom(1)

            isi_table_right_format = workbook.add_format()
            isi_table_right_format.set_font_name('Arial')
            isi_table_right_format.set_font_size(12)
            isi_table_right_format.set_align('right')
            isi_table_right_format.set_align('vcenter')
            isi_table_right_format.set_top(1)
            isi_table_right_format.set_left(1)
            isi_table_right_format.set_right(1)
            isi_table_right_format.set_bottom(1)

            sheet.set_column('A:A', 20)
            sheet.set_column('B:B', 20)
            sheet.set_column('C:C', 20)
            sheet.set_column('D:D', 20)
            sheet.set_column('E:E', 20)
            sheet.set_column('F:F', 20)
            sheet.set_column('G:G', 20)
            sheet.set_column('H:H', 20)

            sheet.write(0, 0, 'No. Nota', header_table_format_white)
            sheet.write(0, 1, 'Jenis Kayu', header_table_format_white)
            sheet.write(0, 2, 'Kode', header_table_format_white)
            sheet.write(0, 3, 'Log Pakai (Pcs)', header_table_format_white)
            sheet.write(0, 4, 'Log Pakai (M3)', header_table_format_white)
            sheet.write(0, 5, 'Hasil Keping', header_table_format_white)
            sheet.write(0, 6, 'Hasil (M3)', header_table_format_white)
            sheet.write(0, 7, 'RENDEMEN', header_table_format_white)

            row1 = 1
            report_lines = request.env['kb.mrp.oven.report.line'].sudo().search(
                [('oven_report_id', '=', rec1.id)],
                order="kb_mrp_oven_id, kb_mrp_oven_line_id, kb_mrp_oven_line_detail_id asc")
            for line in report_lines:
                if line.log_pakai_m3 > 0:
                    rendemen = str(round((line.hasil_m3 / line.log_pakai_m3) * 100, 0))+"%"
                else:
                    rendemen = "0%"
                sheet.write(row1, 0, line.name_header, isi_table_mid_format)
                sheet.write(row1, 1, line.jenis_kayu, isi_table_mid_format)
                sheet.write(row1, 2, line.kode, isi_table_mid_format)
                sheet.write(row1, 3, line.log_pakai_pcs, isi_table_right_format)
                sheet.write(row1, 4, line.log_pakai_m3, isi_table_right_format)
                sheet.write(row1, 5, line.hasil_keping, isi_table_right_format)
                sheet.write(row1, 6, line.hasil_m3, isi_table_right_format)
                sheet.write(row1, 7, rendemen, isi_table_right_format)
                row1 += 1

        for rec2 in wizard:
            sheet = workbook.add_worksheet("Rincian Hasil Oven")
            sheet.set_landscape()
            sheet.set_paper(9)

            header_table_format_kuning = workbook.add_format()
            header_table_format_kuning.set_font_name('Arial')
            header_table_format_kuning.set_font_size(12)
            header_table_format_kuning.set_align('center')
            header_table_format_kuning.set_align('vcenter')
            header_table_format_kuning.set_top(1)
            header_table_format_kuning.set_left(1)
            header_table_format_kuning.set_right(1)
            header_table_format_kuning.set_bottom(1)
            header_table_format_kuning.set_bold()
            header_table_format_kuning.set_bg_color('#f0e973')

            header_table_format_coklat = workbook.add_format()
            header_table_format_coklat.set_font_name('Arial')
            header_table_format_coklat.set_font_size(12)
            header_table_format_coklat.set_align('center')
            header_table_format_coklat.set_align('vcenter')
            header_table_format_coklat.set_top(1)
            header_table_format_coklat.set_left(1)
            header_table_format_coklat.set_right(1)
            header_table_format_coklat.set_bottom(1)
            header_table_format_coklat.set_bold()
            header_table_format_coklat.set_bg_color('#ada184')

            header_table_format_hijau = workbook.add_format()
            header_table_format_hijau.set_font_name('Arial')
            header_table_format_hijau.set_font_size(12)
            header_table_format_hijau.set_align('center')
            header_table_format_hijau.set_align('vcenter')
            header_table_format_hijau.set_top(1)
            header_table_format_hijau.set_left(1)
            header_table_format_hijau.set_right(1)
            header_table_format_hijau.set_bottom(1)
            header_table_format_hijau.set_bold()
            header_table_format_hijau.set_bg_color('#83c977')

            header_table_format_biru = workbook.add_format()
            header_table_format_biru.set_font_name('Arial')
            header_table_format_biru.set_font_size(12)
            header_table_format_biru.set_align('center')
            header_table_format_biru.set_align('vcenter')
            header_table_format_biru.set_top(1)
            header_table_format_biru.set_left(1)
            header_table_format_biru.set_right(1)
            header_table_format_biru.set_bottom(1)
            header_table_format_biru.set_bold()
            header_table_format_biru.set_bg_color('#5096e6')

            header_table_format_white = workbook.add_format()
            header_table_format_white.set_font_name('Arial')
            header_table_format_white.set_font_size(12)
            header_table_format_white.set_align('center')
            header_table_format_white.set_align('vcenter')
            header_table_format_white.set_top(1)
            header_table_format_white.set_left(1)
            header_table_format_white.set_right(1)
            header_table_format_white.set_bottom(1)
            header_table_format_white.set_bold()


            isi_table_mid_format_kuning = workbook.add_format()
            isi_table_mid_format_kuning.set_font_name('Arial')
            isi_table_mid_format_kuning.set_font_size(12)
            isi_table_mid_format_kuning.set_align('center')
            isi_table_mid_format_kuning.set_align('vcenter')
            isi_table_mid_format_kuning.set_top(1)
            isi_table_mid_format_kuning.set_left(1)
            isi_table_mid_format_kuning.set_right(1)
            isi_table_mid_format_kuning.set_bottom(1)
            isi_table_mid_format_kuning.set_bg_color('#f0e973')

            isi_table_mid_format_coklat = workbook.add_format()
            isi_table_mid_format_coklat.set_font_name('Arial')
            isi_table_mid_format_coklat.set_font_size(12)
            isi_table_mid_format_coklat.set_align('center')
            isi_table_mid_format_coklat.set_align('vcenter')
            isi_table_mid_format_coklat.set_top(1)
            isi_table_mid_format_coklat.set_left(1)
            isi_table_mid_format_coklat.set_right(1)
            isi_table_mid_format_coklat.set_bottom(1)
            isi_table_mid_format_coklat.set_bg_color('#ada184')

            isi_table_mid_format_biru = workbook.add_format()
            isi_table_mid_format_biru.set_font_name('Arial')
            isi_table_mid_format_biru.set_font_size(12)
            isi_table_mid_format_biru.set_align('center')
            isi_table_mid_format_biru.set_align('vcenter')
            isi_table_mid_format_biru.set_top(1)
            isi_table_mid_format_biru.set_left(1)
            isi_table_mid_format_biru.set_right(1)
            isi_table_mid_format_biru.set_bottom(1)
            isi_table_mid_format_biru.set_bg_color('#5096e6')

            isi_table_right_format_hijau = workbook.add_format()
            isi_table_right_format_hijau.set_font_name('Arial')
            isi_table_right_format_hijau.set_font_size(12)
            isi_table_right_format_hijau.set_align('right')
            isi_table_right_format_hijau.set_align('vcenter')
            isi_table_right_format_hijau.set_top(1)
            isi_table_right_format_hijau.set_left(1)
            isi_table_right_format_hijau.set_right(1)
            isi_table_right_format_hijau.set_bottom(1)
            isi_table_right_format_hijau.set_bg_color('#83c977')

            isi_table_right_format_biru = workbook.add_format()
            isi_table_right_format_biru.set_font_name('Arial')
            isi_table_right_format_biru.set_font_size(12)
            isi_table_right_format_biru.set_align('right')
            isi_table_right_format_biru.set_align('vcenter')
            isi_table_right_format_biru.set_top(1)
            isi_table_right_format_biru.set_left(1)
            isi_table_right_format_biru.set_right(1)
            isi_table_right_format_biru.set_bottom(1)
            isi_table_right_format_biru.set_bg_color('#5096e6')

            isi_table_left_format = workbook.add_format()
            isi_table_left_format.set_font_name('Arial')
            isi_table_left_format.set_font_size(12)
            isi_table_left_format.set_align('left')
            isi_table_left_format.set_align('vcenter')
            isi_table_left_format.set_top(1)
            isi_table_left_format.set_left(1)
            isi_table_left_format.set_right(1)
            isi_table_left_format.set_bottom(1)

            sheet.set_column('A:A', 20)
            sheet.set_column('B:B', 20)
            sheet.set_column('C:C', 20)
            sheet.set_column('D:D', 20)
            sheet.set_column('E:E', 20)
            sheet.set_column('F:F', 20)
            sheet.set_column('G:G', 20)
            sheet.set_column('H:H', 20)
            sheet.set_column('I:I', 20)
            sheet.set_column('J:J', 20)
            sheet.set_column('K:K', 20)
            sheet.set_column('L:L', 20)
            sheet.set_column('M:M', 20)
            sheet.set_column('N:N', 20)
            sheet.set_column('O:O', 20)
            sheet.set_column('P:P', 20)
            sheet.set_column('Q:Q', 20)
            sheet.set_column('R:R', 20)
            sheet.set_column('S:S', 20)
            sheet.set_column('T:T', 20)
            sheet.set_column('U:U', 20)
            sheet.set_column('V:V', 20)

            sheet.write(0, 0, 'Tgl. Masuk Oven', header_table_format_kuning)
            sheet.write(0, 1, 'Tgl. Selesai Vakum', header_table_format_kuning)
            sheet.write(0, 2, 'Tgl. Selesai Stick', header_table_format_kuning)
            sheet.write(0, 3, 'Tgl. Keluar Oven', header_table_format_kuning)
            sheet.write(0, 4, 'No. Note', header_table_format_kuning)
            sheet.write(0, 5, 'Jenis Kayu', header_table_format_coklat)
            sheet.write(0, 6, 'Kode', header_table_format_coklat)
            sheet.write(0, 7, 'Diameter 1', header_table_format_hijau)
            sheet.write(0, 8, 'Diameter 2', header_table_format_hijau)
            sheet.write(0, 9, 'Panjang', header_table_format_hijau)
            sheet.write(0, 10, 'Log Pakai (Pcs)', header_table_format_hijau)
            sheet.write(0, 11, 'Log Pakai (M3)', header_table_format_hijau)
            sheet.write(0, 12, 'Tebal', header_table_format_biru)
            sheet.write(0, 13, 'Lebar', header_table_format_biru)
            sheet.write(0, 14, 'Panjang', header_table_format_biru)
            sheet.write(0, 15, 'Hasil Keping', header_table_format_biru)
            sheet.write(0, 16, 'Hasil (M3)', header_table_format_biru)
            sheet.write(0, 17, 'Shift', header_table_format_biru)
            sheet.write(0, 18, 'Grade', header_table_format_biru)
            sheet.write(0, 19, 'FSC', header_table_format_biru)
            sheet.write(0, 20, 'Vakum / Celup', header_table_format_biru)
            sheet.write(0, 21, 'Keterangan', header_table_format_white)

            row2 = 1
            report_lines = request.env['kb.mrp.oven.report.line'].sudo().search([('oven_report_id', '=', rec2.id)], order="kb_mrp_oven_id, kb_mrp_oven_line_id, kb_mrp_oven_line_detail_id asc")
            for line in report_lines:
                get_tanggal_masuk_oven_awal = datetime.strptime(str(line.tanggal_masuk_oven), "%Y-%m-%d")
                get_tanggal_masuk_oven = get_tanggal_masuk_oven_awal.strftime("%d/%m/%Y")
                get_tanggal_selesai_vakum_awal = datetime.strptime(str(line.tanggal_selesai_vakum), "%Y-%m-%d")
                get_tanggal_selesai_vakum = get_tanggal_selesai_vakum_awal.strftime("%d/%m/%Y")
                get_tanggal_selesai_stick_awal = datetime.strptime(str(line.tanggal_selesai_stick), "%Y-%m-%d")
                get_tanggal_selesai_stick = get_tanggal_selesai_stick_awal.strftime("%d/%m/%Y")
                get_tanggal_keluar_oven_awal = datetime.strptime(str(line.tanggal_keluar_oven), "%Y-%m-%d")
                get_tanggal_keluar_oven = get_tanggal_keluar_oven_awal.strftime("%d/%m/%Y")
                sheet.write(row2, 0, str(get_tanggal_masuk_oven), isi_table_mid_format_kuning)
                sheet.write(row2, 1, str(get_tanggal_selesai_vakum), isi_table_mid_format_kuning)
                sheet.write(row2, 2, str(get_tanggal_selesai_stick), isi_table_mid_format_kuning)
                sheet.write(row2, 3, str(get_tanggal_keluar_oven), isi_table_mid_format_kuning)
                sheet.write(row2, 4, line.name_header, isi_table_mid_format_kuning)
                sheet.write(row2, 5, line.jenis_kayu, isi_table_mid_format_coklat)
                sheet.write(row2, 6, line.kode, isi_table_mid_format_coklat)
                sheet.write(row2, 7, line.diameter1, isi_table_right_format_hijau)
                sheet.write(row2, 8, line.diameter2, isi_table_right_format_hijau)
                sheet.write(row2, 9, line.panjang_line, isi_table_right_format_hijau)
                sheet.write(row2, 10, line.log_pakai_pcs, isi_table_right_format_hijau)
                sheet.write(row2, 11, line.log_pakai_m3, isi_table_right_format_hijau)
                sheet.write(row2, 12, line.tebal, isi_table_right_format_biru)
                sheet.write(row2, 13, line.lebar, isi_table_right_format_biru)
                sheet.write(row2, 14, line.panjang_detail, isi_table_right_format_biru)
                sheet.write(row2, 15, line.hasil_keping, isi_table_right_format_biru)
                sheet.write(row2, 16, line.hasil_m3, isi_table_right_format_biru)
                sheet.write(row2, 17, line.shift, isi_table_mid_format_biru)
                sheet.write(row2, 18, line.grade, isi_table_mid_format_biru)
                sheet.write(row2, 19, line.fsc, isi_table_mid_format_biru)
                sheet.write(row2, 20, line.vakum_celup, isi_table_mid_format_biru)
                sheet.write(row2, 21, line.keterangan, isi_table_left_format)
                row2 += 1
        workbook.close()
        output.seek(0)
        response.stream.write(output.read())
        output.close()
        return response


class kb_mrp_gudang_kering(http.Controller):
    @http.route(['/kb_mrp_gudang_kering_report/<model("kb.mrp.gudang.kering.report"):wizard>',], type='http', auth="user", csrf=False)
    def get_kb_mrp_gudang_kering_report_excel(self, wizard=None, **args):
        response = request.make_response(
            None,
            headers=[
                ('Content-Type', 'application/vnd.ms-excel'),
                ('Content-Disposition', content_disposition('Gudang Kering Report' + '.xlsx'))
            ]
        )

        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {'in_memory': True})

        for rec1 in wizard:
            sheet = workbook.add_worksheet("Rekap Hasil Gudang Kering")
            sheet.set_landscape()
            sheet.set_paper(9)

            header_table_format_white = workbook.add_format()
            header_table_format_white.set_font_name('Arial')
            header_table_format_white.set_font_size(12)
            header_table_format_white.set_align('center')
            header_table_format_white.set_align('vcenter')
            header_table_format_white.set_top(1)
            header_table_format_white.set_left(1)
            header_table_format_white.set_right(1)
            header_table_format_white.set_bottom(1)
            header_table_format_white.set_bold()

            isi_table_mid_format = workbook.add_format()
            isi_table_mid_format.set_font_name('Arial')
            isi_table_mid_format.set_font_size(12)
            isi_table_mid_format.set_align('center')
            isi_table_mid_format.set_align('vcenter')
            isi_table_mid_format.set_top(1)
            isi_table_mid_format.set_left(1)
            isi_table_mid_format.set_right(1)
            isi_table_mid_format.set_bottom(1)

            isi_table_right_format = workbook.add_format()
            isi_table_right_format.set_font_name('Arial')
            isi_table_right_format.set_font_size(12)
            isi_table_right_format.set_align('right')
            isi_table_right_format.set_align('vcenter')
            isi_table_right_format.set_top(1)
            isi_table_right_format.set_left(1)
            isi_table_right_format.set_right(1)
            isi_table_right_format.set_bottom(1)

            sheet.set_column('A:A', 20)
            sheet.set_column('B:B', 20)
            sheet.set_column('C:C', 20)
            sheet.set_column('D:D', 20)
            sheet.set_column('E:E', 20)
            sheet.set_column('F:F', 20)
            sheet.set_column('G:G', 20)
            sheet.set_column('H:H', 20)

            sheet.write(0, 0, 'No. Nota', header_table_format_white)
            sheet.write(0, 1, 'Jenis Kayu', header_table_format_white)
            sheet.write(0, 2, 'Kode', header_table_format_white)
            sheet.write(0, 3, 'Log Pakai (Pcs)', header_table_format_white)
            sheet.write(0, 4, 'Log Pakai (M3)', header_table_format_white)
            sheet.write(0, 5, 'Hasil Keping', header_table_format_white)
            sheet.write(0, 6, 'Hasil (M3)', header_table_format_white)
            sheet.write(0, 7, 'RENDEMEN', header_table_format_white)

            row1 = 1
            report_lines = request.env['kb.mrp.gudang.kering.report.line'].sudo().search(
                [('gudang_kering_report_id', '=', rec1.id)],
                order="kb_mrp_gudang_kering_id, kb_mrp_gudang_kering_line_id, kb_mrp_gudang_kering_line_detail_id asc")
            for line in report_lines:
                if line.log_pakai_m3 > 0:
                    rendemen = str(round((line.hasil_m3 / line.log_pakai_m3) * 100, 0))+"%"
                else:
                    rendemen = "0%"
                sheet.write(row1, 0, line.name_header, isi_table_mid_format)
                sheet.write(row1, 1, line.jenis_kayu, isi_table_mid_format)
                sheet.write(row1, 2, line.kode, isi_table_mid_format)
                sheet.write(row1, 3, line.log_pakai_pcs, isi_table_right_format)
                sheet.write(row1, 4, line.log_pakai_m3, isi_table_right_format)
                sheet.write(row1, 5, line.hasil_keping, isi_table_right_format)
                sheet.write(row1, 6, line.hasil_m3, isi_table_right_format)
                sheet.write(row1, 7, rendemen, isi_table_right_format)
                row1 += 1

        for rec2 in wizard:
            sheet = workbook.add_worksheet("Rincian Hasil Gudang Kering")
            sheet.set_landscape()
            sheet.set_paper(9)

            header_table_format_kuning = workbook.add_format()
            header_table_format_kuning.set_font_name('Arial')
            header_table_format_kuning.set_font_size(12)
            header_table_format_kuning.set_align('center')
            header_table_format_kuning.set_align('vcenter')
            header_table_format_kuning.set_top(1)
            header_table_format_kuning.set_left(1)
            header_table_format_kuning.set_right(1)
            header_table_format_kuning.set_bottom(1)
            header_table_format_kuning.set_bold()
            header_table_format_kuning.set_bg_color('#f0e973')

            header_table_format_coklat = workbook.add_format()
            header_table_format_coklat.set_font_name('Arial')
            header_table_format_coklat.set_font_size(12)
            header_table_format_coklat.set_align('center')
            header_table_format_coklat.set_align('vcenter')
            header_table_format_coklat.set_top(1)
            header_table_format_coklat.set_left(1)
            header_table_format_coklat.set_right(1)
            header_table_format_coklat.set_bottom(1)
            header_table_format_coklat.set_bold()
            header_table_format_coklat.set_bg_color('#ada184')

            header_table_format_hijau = workbook.add_format()
            header_table_format_hijau.set_font_name('Arial')
            header_table_format_hijau.set_font_size(12)
            header_table_format_hijau.set_align('center')
            header_table_format_hijau.set_align('vcenter')
            header_table_format_hijau.set_top(1)
            header_table_format_hijau.set_left(1)
            header_table_format_hijau.set_right(1)
            header_table_format_hijau.set_bottom(1)
            header_table_format_hijau.set_bold()
            header_table_format_hijau.set_bg_color('#83c977')

            header_table_format_biru = workbook.add_format()
            header_table_format_biru.set_font_name('Arial')
            header_table_format_biru.set_font_size(12)
            header_table_format_biru.set_align('center')
            header_table_format_biru.set_align('vcenter')
            header_table_format_biru.set_top(1)
            header_table_format_biru.set_left(1)
            header_table_format_biru.set_right(1)
            header_table_format_biru.set_bottom(1)
            header_table_format_biru.set_bold()
            header_table_format_biru.set_bg_color('#5096e6')

            header_table_format_white = workbook.add_format()
            header_table_format_white.set_font_name('Arial')
            header_table_format_white.set_font_size(12)
            header_table_format_white.set_align('center')
            header_table_format_white.set_align('vcenter')
            header_table_format_white.set_top(1)
            header_table_format_white.set_left(1)
            header_table_format_white.set_right(1)
            header_table_format_white.set_bottom(1)
            header_table_format_white.set_bold()


            isi_table_mid_format_kuning = workbook.add_format()
            isi_table_mid_format_kuning.set_font_name('Arial')
            isi_table_mid_format_kuning.set_font_size(12)
            isi_table_mid_format_kuning.set_align('center')
            isi_table_mid_format_kuning.set_align('vcenter')
            isi_table_mid_format_kuning.set_top(1)
            isi_table_mid_format_kuning.set_left(1)
            isi_table_mid_format_kuning.set_right(1)
            isi_table_mid_format_kuning.set_bottom(1)
            isi_table_mid_format_kuning.set_bg_color('#f0e973')

            isi_table_mid_format_coklat = workbook.add_format()
            isi_table_mid_format_coklat.set_font_name('Arial')
            isi_table_mid_format_coklat.set_font_size(12)
            isi_table_mid_format_coklat.set_align('center')
            isi_table_mid_format_coklat.set_align('vcenter')
            isi_table_mid_format_coklat.set_top(1)
            isi_table_mid_format_coklat.set_left(1)
            isi_table_mid_format_coklat.set_right(1)
            isi_table_mid_format_coklat.set_bottom(1)
            isi_table_mid_format_coklat.set_bg_color('#ada184')

            isi_table_mid_format_biru = workbook.add_format()
            isi_table_mid_format_biru.set_font_name('Arial')
            isi_table_mid_format_biru.set_font_size(12)
            isi_table_mid_format_biru.set_align('center')
            isi_table_mid_format_biru.set_align('vcenter')
            isi_table_mid_format_biru.set_top(1)
            isi_table_mid_format_biru.set_left(1)
            isi_table_mid_format_biru.set_right(1)
            isi_table_mid_format_biru.set_bottom(1)
            isi_table_mid_format_biru.set_bg_color('#5096e6')

            isi_table_right_format_hijau = workbook.add_format()
            isi_table_right_format_hijau.set_font_name('Arial')
            isi_table_right_format_hijau.set_font_size(12)
            isi_table_right_format_hijau.set_align('right')
            isi_table_right_format_hijau.set_align('vcenter')
            isi_table_right_format_hijau.set_top(1)
            isi_table_right_format_hijau.set_left(1)
            isi_table_right_format_hijau.set_right(1)
            isi_table_right_format_hijau.set_bottom(1)
            isi_table_right_format_hijau.set_bg_color('#83c977')

            isi_table_right_format_biru = workbook.add_format()
            isi_table_right_format_biru.set_font_name('Arial')
            isi_table_right_format_biru.set_font_size(12)
            isi_table_right_format_biru.set_align('right')
            isi_table_right_format_biru.set_align('vcenter')
            isi_table_right_format_biru.set_top(1)
            isi_table_right_format_biru.set_left(1)
            isi_table_right_format_biru.set_right(1)
            isi_table_right_format_biru.set_bottom(1)
            isi_table_right_format_biru.set_bg_color('#5096e6')

            isi_table_left_format = workbook.add_format()
            isi_table_left_format.set_font_name('Arial')
            isi_table_left_format.set_font_size(12)
            isi_table_left_format.set_align('left')
            isi_table_left_format.set_align('vcenter')
            isi_table_left_format.set_top(1)
            isi_table_left_format.set_left(1)
            isi_table_left_format.set_right(1)
            isi_table_left_format.set_bottom(1)

            sheet.set_column('A:A', 20)
            sheet.set_column('B:B', 20)
            sheet.set_column('C:C', 20)
            sheet.set_column('D:D', 20)
            sheet.set_column('E:E', 20)
            sheet.set_column('F:F', 20)
            sheet.set_column('G:G', 20)
            sheet.set_column('H:H', 20)
            sheet.set_column('I:I', 20)
            sheet.set_column('J:J', 20)
            sheet.set_column('K:K', 20)
            sheet.set_column('L:L', 20)
            sheet.set_column('M:M', 20)
            sheet.set_column('N:N', 20)
            sheet.set_column('O:O', 20)
            sheet.set_column('P:P', 20)
            sheet.set_column('Q:Q', 20)
            sheet.set_column('R:R', 20)
            sheet.set_column('S:S', 20)
            sheet.set_column('T:T', 20)

            sheet.write(0, 0, 'Tgl. In GD KD', header_table_format_kuning)
            sheet.write(0, 1, 'Tgl. Out GD KD', header_table_format_kuning)
            sheet.write(0, 2, 'No. Note', header_table_format_kuning)
            sheet.write(0, 3, 'Jenis Kayu', header_table_format_coklat)
            sheet.write(0, 4, 'Kode', header_table_format_coklat)
            sheet.write(0, 5, 'Diameter 1', header_table_format_hijau)
            sheet.write(0, 6, 'Diameter 2', header_table_format_hijau)
            sheet.write(0, 7, 'Panjang', header_table_format_hijau)
            sheet.write(0, 8, 'Log Pakai (Pcs)', header_table_format_hijau)
            sheet.write(0, 9, 'Log Pakai (M3)', header_table_format_hijau)
            sheet.write(0, 10, 'Tebal', header_table_format_biru)
            sheet.write(0, 11, 'Lebar', header_table_format_biru)
            sheet.write(0, 12, 'Panjang', header_table_format_biru)
            sheet.write(0, 13, 'Hasil Keping', header_table_format_biru)
            sheet.write(0, 14, 'Hasil (M3)', header_table_format_biru)
            sheet.write(0, 15, 'Shift', header_table_format_biru)
            sheet.write(0, 16, 'Grade', header_table_format_biru)
            sheet.write(0, 17, 'FSC', header_table_format_biru)
            sheet.write(0, 18, 'Vakum / Celup', header_table_format_biru)
            sheet.write(0, 19, 'Keterangan', header_table_format_white)

            row2 = 1
            report_lines = request.env['kb.mrp.gudang.kering.report.line'].sudo().search([('gudang_kering_report_id', '=', rec2.id)],
                                order="kb_mrp_gudang_kering_id, kb_mrp_gudang_kering_line_id, kb_mrp_gudang_kering_line_detail_id asc")
            for line in report_lines:
                get_tanggal_in_gd_awal = datetime.strptime(str(line.tanggal_in_gd), "%Y-%m-%d")
                get_tanggal_in_gd = get_tanggal_in_gd_awal.strftime("%d/%m/%Y")
                get_tanggal_out_gd_awal = datetime.strptime(str(line.tanggal_out_gd), "%Y-%m-%d")
                get_tanggal_out_gd = get_tanggal_out_gd_awal.strftime("%d/%m/%Y")
                sheet.write(row2, 0, str(get_tanggal_in_gd), isi_table_mid_format_kuning)
                sheet.write(row2, 1, str(get_tanggal_out_gd), isi_table_mid_format_kuning)
                sheet.write(row2, 2, line.name_header, isi_table_mid_format_kuning)
                sheet.write(row2, 3, line.jenis_kayu, isi_table_mid_format_coklat)
                sheet.write(row2, 4, line.kode, isi_table_mid_format_coklat)
                sheet.write(row2, 5, line.diameter1, isi_table_right_format_hijau)
                sheet.write(row2, 6, line.diameter2, isi_table_right_format_hijau)
                sheet.write(row2, 7, line.panjang_line, isi_table_right_format_hijau)
                sheet.write(row2, 8, line.log_pakai_pcs, isi_table_right_format_hijau)
                sheet.write(row2, 9, line.log_pakai_m3, isi_table_right_format_hijau)
                sheet.write(row2, 10, line.tebal, isi_table_right_format_biru)
                sheet.write(row2, 11, line.lebar, isi_table_right_format_biru)
                sheet.write(row2, 12, line.panjang_detail, isi_table_right_format_biru)
                sheet.write(row2, 13, line.hasil_keping, isi_table_right_format_biru)
                sheet.write(row2, 14, line.hasil_m3, isi_table_right_format_biru)
                sheet.write(row2, 15, line.shift, isi_table_mid_format_biru)
                sheet.write(row2, 16, line.grade, isi_table_mid_format_biru)
                sheet.write(row2, 17, line.fsc, isi_table_mid_format_biru)
                sheet.write(row2, 18, line.vakum_celup, isi_table_mid_format_biru)
                sheet.write(row2, 19, line.keterangan, isi_table_left_format)
                row2 += 1
        workbook.close()
        output.seek(0)
        response.stream.write(output.read())
        output.close()
        return response

















#
